N_PARAM: 100
N_DATA : 100
SIN: 4
Effective Dimension: {
  Points from: 0,
  Points to: 1000000,
  Points step: 100,
  Gamma: 1.0,
}
USE_GPU: false
Model: {
  Name: EQM_abbas,
Sin: 4,
Sout: 2,
D_phi: 40,
}
